[FEAT] 식물상세 연결 및 기능 구현
gdsc-konkuk/Plantory-Android pull request #31
Opened 2024-02-03 12:50 UTC by suyeun84

- closed #30 

## 📝 Work Description

- 홈식물카드 click -> 식물상세 전달
- 식물정보 Get -> 프로필에 표시
- 식물히스토리 Get -> 캘린더에 표시 & 바로 반영
- 물주기 Post -> 물주기 icon 변경 & 캘린더에 바로 반영

## 👇PR Point
사진 넣었을 때 정해진 View 크기로 잘려서 나타나는게 아니라 비율이 줄어서 나타나지는데 어떻게 하는게 나을지 의견 부탁드려요!!
그리고 지금 식물id를 가져와서 식물상세 화면에서 식물 전체 Get 해온 다음에 일치하는 id찾아서 나타내주고 있는데, 지금보다 나은 방법이 있을까요?? (홈에서 식물정보를 object로 bundle에 넣어서 전달하면 터지더라구요..)

## 📸 Screenshot

<img width="220" alt="image" src="https://github.com/gdsc-konkuk/Plantory-Android/assets/81475092/6179c976-6615-41c8-b995-cacd9213790c">

## 📣 To Reviewers
사진은 그냥 정해진 임의값 넣어서 나타냈습니다!

2024-02-03 16:04 UTC, sxunea requested changes
일단 주요한 거랑 실행시켰을때 안되는 부분 먼저 남깁니다 ~! 이어서 볼게요 수고했습니다 든든하다 💯

2024-02-03 16:04 UTC, sxunea commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
> +                                )
작성해준 코드처럼 서버에서 받아온 response를 원하는 데이터 클래스로 **변환**하는 로직 (여기서는 mapper)는 보통 `repositoryImpl`에 구현합니다 ! repository와 repositoryImpl가 각각 어떤 패키지에 존재하는지 확인하고 repositoryImpl의 '**구현체**' 로서의 역할을 한번 더 고민해보면 그 이유를 알 수 있지 않을까 생각합니다 : ) !! 

저는 이와 함께 data-DTO / domain-entity 가 뭐가 다른지도 찾아봤을 때 더 이해가 잘되더라구요 혹시 정확하게 알지 못한다면 같이 찾아보고 공부해보는 걸 추천합니다 ㅎㅎㅎ👍

2024-02-03 16:04 UTC, sxunea commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
> +                    ivCalendarRecordedStamp.visibility = if (recordingVisible) View.VISIBLE else View.GONE
👍

2024-02-03 16:04 UTC, sxunea commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
> +        viewModel.getPlantByIdState.flowWithLifecycle(viewLifeCycle).onEach { state ->
getPlantDetailState 어떨까요 ?

2024-02-03 16:04 UTC, sxunea commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
> +                    }else {
현재 '기록하기' 버튼을 클릭해 다른 화면으로 이동했다오면 캘린더가 보이지 않습니다 ~! 
저 코드 블록 안이 비어있는 거랑 관련된 것 같은데 확인하고 수정해주세용

2024-02-03 16:04 UTC, sxunea commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
> +                    firstCallCalendar = false
안의 로직들을 관심사에 따라 어느정도 함수화해 분리해주면 좋을 것 같습니다

2024-02-03 16:04 UTC, sxunea commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
> +            },
`navigateToDetailWithBundle `이런식으로 함수화 해주세요 ~!

2024-02-03 16:22 UTC, l2hyunwoo reviewed
확인해주세요

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantHistory.kt
> +}
<img width="742" alt="스크린샷 2024-02-04 오전 1 07 58" src="https://github.com/gdsc-konkuk/Plantory-Android/assets/54518925/c66fddd7-8be9-412b-9ec1-71c91af26539">

이미 Kotlin의 enum class에는 변수 이름으로 값을 가져올 수 있는 함수가 내재되어있습니다.

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
>  ) {
Q) 왜 Repository 같은 친구들은 Interface를 구현하는 형태로 구현할까요?

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeAdapter.kt
> +                binding.root.setOnClickListener { onItemClick.invoke(data.id) }
```suggestion
                binding.root.setOnClickListener { onItemClick(data.id) }
```

이렇게 적어도 됩니다

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
> +            },
@sxunea 모든 네비게이션 함수에 대해서 멤버함수화를 하는 이유가 따로 있나요?

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/home/HomeFragment.kt
> +    }
이런 형식이라면 전체 util로 빼줄수도 있을 것 같습니다...?

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
> +                updateRequestBody()
updatePlantImage에서 RequestBody까지 한번에 업데이트 시켜줄 수 있지 않을까요?

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
> +            }
postRegisterPlant는 일반함수여서 CoroutineScope에서 launch를 할 필요가 없습니다.

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
> +                    Timber.d("Failure : ${state.msg}")
```suggestion
                    Timber.e("Failure : ${state.msg}")
```

error가 난 경우에는 의미론상 e를 사용하는게 더 좋을 것 같습니다!

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
> +                }
```suggestion
                is UiState.Empty -> Unit

                is UiState.Loading -> Unit
```

이런식으로도 적을 수 있다는 사실!! (권장은 아님, 그냥 이렇게도 적을 수 있다구요)

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantFragment.kt
>      }
SimpleDateFormat한번 검색해보세요

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/AddPlantViewModel.kt
> +            Json.encodeToString(RequestPostRegisterPlantDto.serializer(), plantDto)
오...굳

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailAdapter.kt
> +        val plantDailyRecordsForDate = plantHistories.filter {
```suggestion
        val plantDailyRecordsForDate = currentList.filter {
```

이렇게 현재 adapter내의 list를 다시 가져올 수 있습니다.

2024-02-03 16:22 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
>      }
클릭리스너에 collect를 달아버리면 어떻게 될까요?

2024-02-04 07:13 UTC, sxunea approved these changes

2024-02-04 07:44 UTC, suyeun84 commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/domain/entity/PlantHistory.kt
> +}
와우!

2024-02-04 08:42 UTC, suyeun84 commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailViewModel.kt
> +                                )
더 찾아보고 공부해야겠네요!!❤️👍

2024-02-04 09:31 UTC, suyeun84 commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
>      }
클릭 이벤트는 메인 스레드에서 발생하고 collect는 백그라운드에서 작동하니까 작업이 수행되지 않을수 있는건가요..?!

2024-02-04 09:48 UTC, suyeun84 commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/data/source/PlantDataSource.kt
>  ) {
Repository는 domain에 위치하고 RepositoryImpl는 data에 위치하는데 domain이 data에 대한 의존성을 가지지 않게 하고, data의 변경에 의해 domain이 변하는 걸 막아줍니다. 또한 의존성을 가지지 않으므로 코드의 유지보수를 더 수월하게 만들어주기 때문에 interface로 구현합니다!

2024-02-04 10:02 UTC, l2hyunwoo commented on app/src/main/java/kr/ac/konkuk/gdsc/plantory/presentation/plant/DetailFragment.kt
>      }
한번 실행해보시겠어요? 그리고 반응형프로그래밍에서 데이터가 변경되는 것을 감지하는 프로세스를 다시한번 생각해볼 필요가 있을 것 같습니다

2024-02-04 17:03 UTC, merged